name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    name: mix test (Erlang/OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.2.6
            otp: 18.3.4.11
          - elixir: 1.10.4
            otp: 23.0.3
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix deps.get --only test
      - run: mix test

  check_formatted:
    name: Check formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: 23.0.3
          elixir-version: 1.10.4
      - run: mix format --check-formatted
